name: OBSVAD Windows Build

on:
  push:
    branches: [ 'master' ]
    tags:
      - '*.*.*'

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.x'
      - name: Install action dependencies
        run: pip install flake8 pyinstaller
      - name: Install application dependencies
        run: pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Build executable
        run: pyinstaller obs_vad.spec
      - name: Determine Reference Type
        id: determine_ref
        uses: actions/github-script@v5
        with:
          script: |
            const refType = `${{ github.ref }}`.startsWith('refs/tags/')? 'tag' : 'branch';
            return { refType };
      - name: Set IS_SEMANTIC_VERSION
        id: set_env
        run: |
          if (${{ steps.determine_ref.outputs.refType }} == 'tag') {
            echo "IS_SEMANTIC_VERSION=true"
          } else {
            echo "IS_SEMANTIC_VERSION=false"
          }
        shell: pwsh
      - name: Create Release
        if: env.IS_SEMANTIC_VERSION == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        if: env.IS_SEMANTIC_VERSION == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/OBSVad.exe
          asset_name: OBSVad.exe
          asset_content_type: application/octet-stream
